### ISSUE TITLE
Suggestion: Shorter keyword than `target`

### ISSUE THREAD

**Issue by Boscop** [chancancode/rust-delegate#12]
`target` is quite long to type, and it becomes noticeable when using the `delegate` macro a lot.
Could we shorten it for the next version of this crate? :)
E.g. how about using `to` as keyword, it also reads nicely, like "delegate to self.foo":
```rust
impl<S: Selectable> Switcher2<S> {
    delegate! {
        to self.switcher {
            pub fn page(&self) -> S;

            pub fn set_col(&mut self, col: Col);

            pub fn set_selected_brightness(&mut self, b: f32);
        }
    }
}
```
If you don't like `to`, how about `for`? It reads less like an English sentence compared to `to`, but has the benefit of getting syntax-highlighted in editors, and looks nice/familiar because it opens a block:
```rust
impl<S: Selectable> Switcher2<S> {
    delegate! {
        for self.switcher {
            pub fn page(&self) -> S;

            pub fn set_col(&mut self, col: Col);

            pub fn set_selected_brightness(&mut self, b: f32);
        }
    }
}
```
(Another possibility would be `as` but that already has a semantic connotation that could confuse readers in this context.)

**Comment by Kobzol** [comment]
`to` sounds really nice! `Delegate to self.field` seems like a very elegant sentence to read. 

`for` and `as` seem a bit weird to me in this place. Another one that comes to mind is `with`, but `to` seems better to me.

https://github.com/chancancode/rust-delegate/pull/13
