### ISSUE TITLE
New Release Please

### ISSUE THREAD

**Issue by Emoun** [chancancode/rust-delegate#20]
Hi,

I've been following the progress on this crate closely, as I needed features that weren't available yet. However, I can now see that master has all the features I need to use this crate fully (namely arbitrary expressions as "targets" for the delegation).
Therefore, can I ask you to release a new version of the crate to crates.io, so that I can depend on that instead of having to depend directly on the repo?

Thanks for all your work, this is a great crate.

**Comment by Kobzol** [comment]
Hi! Thanks for reminding me of this. I pushed the last change (`target_method` becomes `call`) and updated the README to hopefully make it shorter and more readable. The current version from master was pushed to cargo as 0.4.0 (https://crates.io/crates/delegate/0.4.0).

**Comment by Emoun** [comment]
Thanks for the quick response.
Looks great and I can report the new release works as expected for me.
