### ISSUE TITLE
Arbitrary inner field expressions

### ISSUE THREAD

**Issue by Boscop** [chancancode/rust-delegate#24]
The readme says:

> Use an arbitrary inner field expression

But this fails:

```rust
	delegate! {
		to self.pass_output_textures[self.image_pass_idx] {
			pub fn input_texture(&self) -> &Texture2d;
		}
	}
```

> error: proc macro panicked
help: message: Use a field expression to select delegator (e.g. self.inner)

What's the right way to do this? :)

**Comment by Kobzol** [comment]
Ahem, maybe the term `arbitrary` was a bit too optimistic :-) Please try `0.4.3` (just published it), it should now just take the expression and use it, so as long as it compiles, it should work.

**Comment by Boscop** [comment]
Thanks :)
