### ISSUE TITLE
Better approach for Edition 2018 macro imports 

### ISSUE THREAD

**Issue by abreis** [chancancode/rust-delegate#6]
With Rust 2018, the recommended approach is now to `use` macros instead of `extern crate`.

For `delegate`, this now looks something like:
```rust
use delegate::{delegate, delegate__parse, delegate__ensure_self, delegate__expand};
```

If possible, group all these macros under a single import.

**Comment by abreis** [comment]
I haven't looked at the new procedural macros yet, but I believe so, yes. It would be a pretty major rewrite of this crate, though.

**Comment by chancancode** [comment]
Yep. We can do those two things separately. Would using `$crate::delegate__parse! { ... }` internally remove the need of importing those macros from the user's side?

**Comment by abreis** [comment]
I think so, yes, or perhaps we can add `use` statements within the macro if that doesn't work (thought it doesn't look very nice).

Let me give it a try and report back. If it works I'll open a PR.
