### ISSUE TITLE
Delegation to members of members?

### ISSUE THREAD

**Issue by Boscop** [chancancode/rust-delegate#9]
Delegation to members of members doesn't seem to work, and the error message is wrong:

![image](https://user-images.githubusercontent.com/535593/66169190-d9a04c00-e63f-11e9-8ac7-31272c8f02ba.png)

Can you please add delegation to `(members of)+` members? :)
(Any depth should work)

**Comment by Kobzol** [comment]
This should be fixed by https://github.com/chancancode/rust-delegate/pull/8.

**Comment by Boscop** [comment]
Yes, thanks :)
